name: Build

on: push

jobs:
  build-posix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [clang, gcc]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build bdiff with CMake
      run: |
        export CC=${{ matrix.toolchain }}
        cmake -B build .
        cmake --build build
    - uses: actions/upload-artifact@v2
      with:
        name: bdiff-${{ matrix.os }}-${{ matrix.toolchain }}-${{ github.sha }}
        path: build/bdiff
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build bdiff with CMake
      run: |
        cmake -B build .
        cmake --build build
    - uses: actions/upload-artifact@v2
      with:
        name: bdiff-windows-msvc-${{ github.sha }}
        path: build/bdiff
