name: CI

on: push

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-tidy
      run: sudo apt-get install clang-tidy
    - name: Lint with clang-tidy
      run: FILES=$(find src/ -name *.c -o -name *.h)
        clang-tidy "$FILES" --config='' -- -Iinclude
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Stylecheck with clang-format
        run: FILES=$(find src/ -name *.c -o -name *.h)
          clang-format $FILES
